### ISSUE TITLE
`P1 | Onboarding`: Assignment report: Onboarding

### ISSUE THREAD

**Issue by rasmus-d** [KTH-DD2480-Fundsoft/pdm-assignment-3#1]
Complete the segment on evaluating the pdm projects onboarding. For this we need a branch, never to be merged to main, where we can work on the assignment report in peace. Create a branch and add the report template.

**Comment by rasmus-d** [comment]
I've written a few scentances, someone please take a look, SHA: be4fa86b8bf740ac0cfc5fb54ef5fef82e096ea5

**Comment by dantevi** [comment]
Let's close this and open other issues for further iterations on the Onboarding segment.
