### ISSUE TITLE
`P2e | Part 1`: Manually count the complexity of `_parse_setup_cfg`

### ISSUE THREAD

**Issue by rasmus-d** [KTH-DD2480-Fundsoft/pdm-assignment-3#10]
Count the complexity of `_parse_setup_cfg@6-88@src/pdm/models/in_process/parse_setup.py` manually. Put the results in a file `_parse_setup_cfg_complexity.md` on a branch, not to be merged to main.

Also document the purpose of the function, why it is complex, why it should be or why it shouldn't be. Put this in the same file.

**Comment by dantevi** [comment]
Closed by #49
