### ISSUE TITLE
`P5 | Part 2, Task 2`: Coverage improvement

### ISSUE THREAD

**Issue by rasmus-d** [KTH-DD2480-Fundsoft/pdm-assignment-3#13]
Check the [coverage report](https://github.com/KTH-DD2480-Fundsoft/pdm-assignment-3/blob/snapshot-complexity-coverage/coverage.txt) and pick, for 5(?),10(?),20(?) (Instructions are unclear, awaiting clarification) different tests:
    1. Identify the requirements that are tested or untested by the given test suite.
    2. Document the requirements (as comments), and use them later as assertions.
    3. Create new test cases as needed to improve branch coverage in the given functions. Can you call the function directly? Can you expand on existing tests? Do you have to add additional interfaces to the system (as public methods) to make it possible to set up test data structures?
    4. If you have 100 % branch coverage, you can choose other functions or think about path coverage. You may cover all branches in a function, but what does this mean for the combination of branches? Consider the existing tests by hand and check how they cover the branches (in which combinations)

After picking a test suite, create a new issue `P5x` (`x \elem {a,b,c,d,e}`) detailing exactly what tests are being worked on. Branch from main to a feature branch and make the changes. Use [this](https://github.com/pdm-project/pdm/blob/main/CONTRIBUTING.md) for guidance. 

Definition of Done: All changes (all subtasks) merged to main.

**Comment by dantevi** [comment]
Can we close this and let the other issues regarding coverage dictate whether this part and task of the assignment is done?

**Comment by Stenmarken** [comment]
All coverage improvement has been merged to feature/13/improve-coverage
