### ISSUE TITLE
`P4d | Part 2, Task 1`: Implement ad_hoc branch coverage for `synchronize`

### ISSUE THREAD

**Issue by lskare** [KTH-DD2480-Fundsoft/pdm-assignment-3#15]
Add checks for each branch in the function `synchronize@385-467@./src/pdm/installers/synchronizers.py` . Use the dictionary defined in issue https://github.com/KTH-DD2480-Fundsoft/pdm-assignment-3/issues/11

**Comment by dantevi** [comment]
If the changes are already included into the branch `feature/11/ad-ho-branch-cover`, then this issue has effectively been merged and should be closed.

**Comment by dantevi** [comment]
Closed by commit 00bd38c
