### ISSUE TITLE
`P5d | Part 2, Task 2`: Add coverage for `synchronize`

### ISSUE THREAD

**Issue by lskare** [KTH-DD2480-Fundsoft/pdm-assignment-3#23]
Description:
The aim is to write 4 new tests for the `synchronize` function that improves its branch coverage.

DoD:
4 newly written or expanded unit tests in a reasonable test file

See issue #13 for further instructions

**Comment by dantevi** [comment]
Is there a branch for this?

**Comment by dantevi** [comment]
There is locally. Work in progress.

**Comment by Stenmarken** [comment]
Closing this since this is merged
