### ISSUE TITLE
`P6 | Part 2, Task 4`: Assignment report: add paragraph regarding ESSENCE standard

### ISSUE THREAD

**Issue by Stenmarken** [KTH-DD2480-Fundsoft/pdm-assignment-3#3]
From the assignment instructions: Assess your way of working (p. 58 in the Essence standard v1.2) by evaluating the checklist on p. 60:
In what state are you in? Why? What are obstacles to reach the next state? How have you improved during the course, and where is more improvement possible?

**Comment by lskare** [comment]
Merged to report branch
