### ISSUE TITLE
`P3e | Part 2, Task 3`: Implement refactoring plan of _merge_bounds_and_excludes

### ISSUE THREAD

**Issue by Stenmarken** [KTH-DD2480-Fundsoft/pdm-assignment-3#31]
Description:
Write a detailed plan of how one would refactor the function _merge_bounds_and_excludes with a CCN complexity of 21 into smaller units in order to reduce the complexity of the function. The CCN complexity should be reduced with atleast 35% in order to pass the P+ criteria. 

DoD:
A markdown file is created in the folder "Refactoring plans" which includes a detailed plan of the refactoring along with code examples.

**Comment by dantevi** [comment]
Closed by #35
