### ISSUE TITLE
`P3d | Part 2, Task 3`: Implement plan for refactoring function `do_update`

### ISSUE THREAD

**Issue by rasmus-d** [KTH-DD2480-Fundsoft/pdm-assignment-3#33]
Description:
Write a detailed plan of how one would refactor the function `do_update` with a CCN complexity of `35` into smaller units in order to reduce the complexity of the function. The CCN complexity should be reduced with atleast 35% in order to pass the P+ criteria. Include code examples to clarify and better explain the refactoring plan

DoD:
A markdown file is created in the folder "Refactoring plans" which includes a detailed plan of the refactoring along with code examples

**Comment by dantevi** [comment]
Completed with #34
