### ISSUE TITLE
`P2 | Part 1`: Investigate 5 functions for cyclomatic complexity measurement

### ISSUE THREAD

**Issue by Stenmarken** [KTH-DD2480-Fundsoft/pdm-assignment-3#4]
Manually calculate the cyclomatic complexity for 5 functions.

Here's the formula from [wikipedia](https://en.wikipedia.org/wiki/Cyclomatic_complexity):

`M = E - N + 2P`, where 
`E = number of edges in the cfg`
`N = number of nodes in the cfg`
`P = number of connected components in the cfg`

Also document the purpose of the function, why it is complex, why it should be or why it shouldn't be.

**Comment by rasmus-d** [comment]
Here are the largest functions:
```
105     35    669      9     110 do_update@91-200@src/pdm/cli/commands/update.py
98     34    666      7     101 do_add@87-187@src/pdm/cli/commands/add.py
89     19    651     10      94 do_lock@39-132@src/pdm/cli/actions.py
62     18    479      1      83 synchronize@385-467@src/pdm/installers/synchronizers.py
60     29    505      1      83 _parse_setup_cfg@6-88@src/pdm/models/in_process/parse_setup.py
```

**Comment by rasmus-d** [comment]
As I understand it we're supposed to manually count the complexity of 5 functions (1 each). But document 10 functions (2 each) that are of high complexity, why they are/should be/should not be -- complex.

**Comment by dantevi** [comment]
I'll close this because we have decided which functions we are going to calculate the CCN for.
