### ISSUE TITLE
`P5e | Part 2, Task 2`: Add coverage for `_build_pyspec_from_marker`

### ISSUE THREAD

**Issue by sebastianmonten** [KTH-DD2480-Fundsoft/pdm-assignment-3#42]
add tests to improve coverage in `_build_pyspec_from_marker@91-126@./pdm/models/markers.py`

CCN = 19, Cover = 82% for `markers.py`

see #13

**Comment by Stenmarken** [comment]
Closed with merge to improve coverage branch
