### ISSUE TITLE
`P3 | Part 2, Task 3`: Add refactoring plan for `_parse_setup_cfg`

### ISSUE THREAD

**Issue by sebastianmonten** [KTH-DD2480-Fundsoft/pdm-assignment-3#77]
description: branch from `report` and add refactoring plan for function `_parse_setup_cfg@6-88@src/pdm/models/in_process/parse_setup.py` in a markdown file in the Refactoring-plans directory. See `Refactoring the function synchronize from synchronize@385-467@./src/pdm/installers/synchronizers.py` for inspiration. 

definition of done: plan added to a markdown file in Refactoring-plans and branch merged back to `report`.

**Comment by dantevi** [comment]
Closed by #84
