### ISSUE TITLE
`P3`: Refactor `_parse_setup_cfg` according to the refactoring plan

### ISSUE THREAD

**Issue by sebastianmonten** [KTH-DD2480-Fundsoft/pdm-assignment-3#81]
description: implement the refactoring described in `Fundsoft/Refactoring-plans/Refactor-plan-function-synchronize.md` and evaluate new CCN. if not 18 or less refactor further according to suggestions in the refactoring plan. see #77

this is done on a branch from `main`

definition of done: function `_parse_setup_cfg` is refactored and has a new CCN of 18 or less. the changes are merged into `feature/65/refactor`

**Comment by dantevi** [comment]
Closed by #85
